version: '2'

services:

  {% if docker_port_forward.postgis is defined %}

  postgis:
    ports:
      # - "6543:5432"
      {% if docker_port_forward.postgis.postgis is defined %}

      - "{{ docker_port_forward.postgis.postgis }}:5432"

      {% endif %}
  {% endif %}

  geoserver:
    image: geonode/geoserver:alias
    links:
      - postgis
    {% if docker_port_forward.geoserver is defined %}

    ports:
      # - "9003:80"
      {% if docker_port_forward.geoserver.http is defined %}

      - "{{ docker_port_forward.geoserver.http }}:8080"

      {% endif %}
    {% endif %}

    volumes_from:
      - data_dir_conf
    environment:
      - DJANGO_URL={{ django.GEONODE_BASE_URL }}
      - SITEURL={{ django.SITEURL }}
      - GEOSERVER_LOCATION={{ django.GEOSERVER_LOCATION }}
      - GEOSERVER_PUBLIC_LOCATION={{ django.GEOSERVER_PUBLIC_LOCATION }}

    network_mode: "bridge"

  data_dir_conf:
    image: geonode/geoserver_data:2.9.x-oauth2
    container_name: geoserver_data_dir
    command: /bin/true
    volumes:
      - /geoserver_data/data
    network_mode: "bridge"

  django:
    volumes:
      - './pycharm_helpers/django:/root/.pycharm_helpers'
    environment:
      - DEBUG={{ django.DEBUG }}
      - ALLOWED_HOSTS={{ django.ALLOWED_HOSTS }}
      - SITEURL={{ django.SITEURL }}
      - OGC_BACKEND=geonode.{{ ogc_backend }}
      - USE_GEOSAFE={{ use_geosafe }}
      - GEOSERVER_BASE_URL={{ django.GEOSERVER_BASE_URL }}
      - GEOSERVER_LOCATION={{ django.GEOSERVER_LOCATION }}
      - GEOSERVER_PUBLIC_LOCATION={{ django.GEOSERVER_PUBLIC_LOCATION }}
    {% if django.command is defined %}

    command: {{ django.command }}

    {% endif %}
    {% if docker_port_forward.django is defined %}

    ports:
      # - "9000:22"
      {% if docker_port_forward.django.ssh is defined %}

      - "{{ docker_port_forward.django.ssh }}:22"

      {% endif %}
    {% endif %}

    links:
      - geoserver

  {% if docker_port_forward.web is defined %}

  web:

    {% if web.command is defined %}

    command: {{ web.command }}

    {% endif %}

    ports:
      # - "80:80"
      {% if docker_port_forward.web.http is defined %}

      - "{{ docker_port_forward.web.http }}:80"

      {% endif %}
  {% endif %}

  celery:
    volumes:
      - './pycharm_helpers/celery:/root/.pycharm_helpers'
    environment:
      - DEBUG={{ django.DEBUG }}
      - ALLOWED_HOSTS={{ django.ALLOWED_HOSTS }}
      - SITEURL={{ django.SITEURL }}
      - OGC_BACKEND=geonode.{{ ogc_backend }}
      - USE_GEOSAFE={{ use_geosafe }}
      - GEOSERVER_BASE_URL={{ django.GEOSERVER_BASE_URL }}
      - GEOSERVER_LOCATION={{ django.GEOSERVER_LOCATION }}
      - GEOSERVER_PUBLIC_LOCATION={{ django.GEOSERVER_PUBLIC_LOCATION }}
    {% if celery.command is defined %}

    command: {{ celery.command }}

    {% endif %}
    {% if docker_port_forward.celery is defined %}

    ports:
      # - "9001:22"
      {% if docker_port_forward.celery.ssh is defined %}
      - "{{ docker_port_forward.celery.ssh }}:22"
      {% endif %}
    {% endif %}

    links:
      - geoserver
