version: '2'
volumes:
  geoserver-data-dir:
services:

  {% if docker_port_forward.db is defined %}

  db:
    ports:
      # - "6543:5432"
      {% if docker_port_forward.db.db is defined %}

      - "{{ docker_port_forward.db.db }}:5432"

      {% endif %}
  {% endif %}

  geoserver:
    image: geosolutionsit/geoserver-docker:2.12.x
    links:
      - db
    {% if docker_port_forward.geoserver is defined %}

    ports:
      # - "9003:80"
      {% if docker_port_forward.geoserver.http is defined %}

      - "{{ docker_port_forward.geoserver.http }}:8080"

      {% endif %}
    {% endif %}

    volumes:
      - geoserver-data-dir:/geoserver_data/data
    environment:
      - DJANGO_URL={{ django.environment.GEONODE_BASE_URL }}
      - SITEURL={{ django.environment.SITEURL }}
      - GEOSERVER_LOCATION={{ django.environment.GEOSERVER_LOCATION }}
      - GEOSERVER_PUBLIC_LOCATION={{ django.environment.GEOSERVER_PUBLIC_LOCATION }}
      - GEOSERVER_ADMIN_PASSWORD={{ django.environment.GEOSERVER_ADMIN_PASSWORD }}
      - NGINX_BASE_URL={{ django.environment.SITEURL }}geoserver

    network_mode: "bridge"

  data_dir_conf:
    image: geosolutionsit/geoserver_data:2.12.x
    command: /bin/true
    volumes:
      - geoserver-data-dir:/geoserver_data/data
    network_mode: "bridge"

  django:
    volumes:
      - './pycharm_helpers/django:/root/.pycharm_helpers'
    environment:
      USE_GEOSAFE: "{{ use_geosafe }}"
      OGC_BACKEND: "geonode.{{ ogc_backend }}"

      {% for key, value in django.environment.iteritems() %}

      {{ key }}: "{{ value }}"

      {% endfor %}

    {% if django.command is defined %}

    command: {{ django.command }}

    {% endif %}
    {% if docker_port_forward.django is defined %}

    ports:
      # - "9000:22"
      {% if docker_port_forward.django.ssh is defined %}

      - "{{ docker_port_forward.django.ssh }}:22"

      {% endif %}
    {% endif %}

    links:
      - geoserver

  {% if docker_port_forward.web is defined %}

  web:

    {% if web.command is defined %}

    command: {{ web.command }}

    {% endif %}

    links:
      - geoserver
    environment:
      GEOSERVER_FORWARD: 1
    ports:
      # - "80:80"
      {% if docker_port_forward.web.http is defined %}

      - "{{ docker_port_forward.web.http }}:80"

      {% endif %}
  {% endif %}

  celery:
    volumes:
      - './pycharm_helpers/celery:/root/.pycharm_helpers'
    environment:
      USE_GEOSAFE: "{{ use_geosafe }}"
      OGC_BACKEND: "geonode.{{ ogc_backend }}"

      {% for key, value in django.environment.iteritems() %}

      {{ key }}: "{{ value }}"

      {% endfor %}
    {% if celery.command is defined %}

    command: {{ celery.command }}

    {% endif %}
    {% if docker_port_forward.celery is defined %}

    ports:
      # - "9001:22"
      {% if docker_port_forward.celery.ssh is defined %}
      - "{{ docker_port_forward.celery.ssh }}:22"
      {% endif %}
    {% endif %}

    links:
      - geoserver
