sudo: required

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

services:
  - docker

env:
  - ALL_FILE: 'all.travis.geosafe.yml'
  - ALL_FILE: 'all.travis.qgis.yml'
  - ALL_FILE: 'all.travis.geoserver.yml'

branches:
  only:
    - develop

before_install:
  # install ansible
  - sudo apt-get -y update
  - sudo apt-get -y install libssl-dev
  - sudo pip install ansible

install:
  # setup files
  - pushd deployment
  - cp ansible/development/group_vars/${ALL_FILE} ansible/development/group_vars/all.yml
  - make setup-ansible ANSIBLE_ARGS="--extra-vars='ansible_sudo_pass=\"\"' --extra-vars='pycharm_version=\"\"' --skip-tags=development"
  # show docker-compose.override.yml for debugging
  - cat docker-compose.override.yml
  - popd

script:
  - pushd deployment
  - make build-geonode-core
  - make build
  - make up
  - until make sync; do echo "Retrying"; sleep 5; done
  - popd
