---
# Edit or use this files as template to configure ansible variable,
# then save it as filename: "all" in this folder.

# Use either qgis_server or geoserver
ogc_backend: qgis_server
# set to True or False to include geosafe in the orchestration
use_geosafe: True

# put your linux/mac user here
remote_user: vasuse7en
# put your linux/mac group here
remote_group: vasuse7en
# put project path
project_path: "~/workspace/dev/geosafe/vasuse7en github/docker-geosafe/docker-geosafe"

# component path relative to project_path
component_path:
  geonode: "/src/geonode"
  geosafe: "/src/geosafe"
  inasafe: "/src/inasafe"
  otf_project: "/src/otf-project"

docker_port_forward:
  web:
    http: 80

qgis_server:
  DEBUG: True
  QGIS_LOG_FILE: /tmp/qgis-server/qgis.log
  QGIS_SERVER_LOG_FILE: /tmp/qgis-server/qgis-server.log
  QGIS_DEBUG: 0
  QGIS_SERVER_LOG_LEVEL: 0

django:
  DEBUG: False
  ALLOWED_HOSTS: "['localhost','django','192.168.100.223']"
  # put your ip address of your interface
  SITEURL: http://192.168.100.223/
  GEONODE_BASE_URL: http://192.168.100.223/
  QGIS_SERVER_URL: http://qgis-server/
  # GeoSAFE specific settings
  USE_LAYER_FILE_ACCESS: True
  INASAFE_LAYER_DIRECTORY: "/home/geosafe/media/"
  INASAFE_LAYER_DIRECTORY_BASE_PATH: "/usr/src/app/geonode/uploaded/"
  GEOSAFE_IMPACT_OUTPUT_DIRECTORY: "/home/geosafe/impact_layers"
  INASAFE_IMPACT_BASE_URL: "/output/"
  USE_LAYER_HTTP_ACCESS: False
  INASAFE_ANALYSIS_RUN_TIME_LIMIT: 600
  INASAFE_ANALYSIS_AREA_LIMIT: 1000000000

celery:
  DEBUG: False

inasafe_headless:
  INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR: /home/output/
  INASAFE_HEADLESS_DEPLOY_OUTPUT_URL: http://inasafe-output/output/
  QGIS_LOG_FILE: /tmp/inasafe/realtime/logs/qgis.log
  QGIS_DEBUG_FILE: /tmp/inasafe/realtime/logs/qgis-debug.log
  QGIS_DEBUG: 0
  INASAFE_WORK_DIR: /tmp/inasafe

inasafe_headless_analysis:
  INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR: /home/output/
  INASAFE_HEADLESS_DEPLOY_OUTPUT_URL: http://inasafe-output/output/
  QGIS_LOG_FILE: /tmp/inasafe/realtime/logs/qgis.log
  QGIS_DEBUG_FILE: /tmp/inasafe/realtime/logs/qgis-debug.log
  QGIS_DEBUG: 0
  INASAFE_WORK_DIR: /tmp/inasafe
