---
# Edit or use this files as template to configure ansible variable,
# then save it as filename: "all" in this folder.

# Use either qgis_server or geoserver
ogc_backend: geoserver
# set to True or False to include geosafe in the orchestration
use_geosafe: False

# put your linux/mac user here
remote_user: travis
# put your linux/mac group here
remote_group: travis
# put project path
project_path: "/home/travis/build/kartoza/docker-geosafe"

# component path relative to project_path
component_path:
  geonode: "/src/geonode"

docker_port_forward:
  web:
    http: 80

web:
  command: prod

django:
  environment:
    DEBUG: False
    # put your ip address of your interface to SITEURL and GEONODE_BASE_URL
    ALLOWED_HOSTS: "['172.17.0.1','localhost','django']"
    SITEURL: http://172.17.0.1/
    GEONODE_BASE_URL: http://172.17.0.1/
    GEONODE_LB_HOST_IP: 172.17.0.1
    GEONODE_LB_PORT: 80
    UWSGI_CMD: uwsgi --ini /uwsgi.conf
    # Settings for GeoServer
    GEOSERVER_BASE_URL: http://geoserver:8080/geoserver/
    GEOSERVER_LOCATION: http://geoserver:8080/geoserver/
    GEOSERVER_PUBLIC_LOCATION: http://172.17.0.1:8080/geoserver/
    GEOSERVER_ADMIN_PASSWORD: admingeoserver

celery:
  command: celery worker --app=geonode.celery_app:app -B -l INFO
