---
# Edit or use this files as template to configure ansible variable,
# then save it as filename: "all" in this folder.

# Use either qgis_server or geoserver
ogc_backend: qgis_server
# set to True or False to include geosafe in the orchestration
use_geosafe: False

# put your linux/mac user here
remote_user: travis
# put your linux/mac group here
remote_group: travis
# put project path
project_path: "/home/travis/build/kartoza/docker-geosafe"

# component path relative to project_path
component_path:
  geonode: "/src/geonode"
  otf_project: "/src/otf-project"

docker_port_forward:
  web:
    http: 80

qgis_server:
  environment:
    DEBUG: True
    QGIS_LOG_FILE: /tmp/qgis-server/qgis.log
    QGIS_SERVER_LOG_FILE: /tmp/qgis-server/qgis-server.log
    QGIS_DEBUG: 0
    # Log level 0 is the lowest (catch all), 5 is the highest (only fatal error)
    QGIS_SERVER_LOG_LEVEL: 0

web:
  command: prod

django:
  environment:
    DEBUG: True
    # put your ip address of your interface to SITEURL and GEONODE_BASE_URL
    ALLOWED_HOSTS: "['172.17.0.1','localhost','django']"
    SITEURL: http://172.17.0.1/
    GEONODE_BASE_URL: http://172.17.0.1/
    GEONODE_LB_HOST_IP: 172.17.0.1
    GEONODE_LB_PORT: 80
    UWSGI_CMD: uwsgi --ini /uwsgi.conf
    # Settings for qgis server
    QGIS_SERVER_URL: http://qgis-server/

celery:
  command: celery worker --app=geonode.celery_app:app -B -l INFO
