---
# Edit or use this files as template to configure ansible variable,
# then save it as filename: "all" in this folder.

# Use either qgis_server or geoserver
ogc_backend: geoserver
# set to True or False to include geosafe in the orchestration
use_geosafe: False

# put your linux/mac user here
remote_user: travis
# put your linux/mac group here
remote_group: travis
# put project path
project_path: "/home/travis/build/kartoza/docker-geosafe"

# component path relative to project_path
component_path:
  geonode: "/src/geonode"

docker_port_forward:
  web:
    http: 80

web:
  command: prod

django:
  DEBUG: False
  ALLOWED_HOSTS: "['localhost','django']"
  # put your ip address of your interface
  GEONODE_BASE_URL: http://django:8000/
  SITEURL: http://172.17.0.1/
  GEOSERVER_BASE_URL: http://geoserver:8080/geoserver/
  GEOSERVER_LOCATION: http://geoserver:8080/geoserver/
  GEOSERVER_PUBLIC_LOCATION: http://172.17.0.1:8080/geoserver/

celery:
  DEBUG: False
  command: celery worker --app=geonode.celery_app:app -B -l INFO
