---
# Edit or use this files as template to configure ansible variable,
# then save it as filename: "all" in this folder.

# Use either qgis_server or geoserver
ogc_backend: qgis_server
# set to True or False to include geosafe in the orchestration
use_geosafe: True

# put your linux/mac user here
remote_user: user
# put your linux/mac group here
remote_group: group
# put project path
project_path: "/Users/user/Documents/WorkingDir/Projects/InaSAFE/docker-geosafe"

# component path relative to project_path
component_path:
  geonode: "/src/geonode"
  geosafe: "/src/geosafe"
  inasafe: "/src/inasafe"
  otf_project: "/src/otf-project"

docker_port_forward:
  postgis:
    postgis: 6543
  geoserver:
    http: 8080
  qgis_server:
    http: 9003
  django:
    ssh: 9000
  web:
    http: 80
  celery:
    ssh: 9001
  inasafe_headless:
    ssh: 9002
  inasafe_headless_analysis:
    ssh: 9004

qgis_server:
  DEBUG: True
  QGIS_LOG_FILE: /tmp/qgis-server/qgis.log
  QGIS_SERVER_LOG_FILE: /tmp/qgis-server/qgis-server.log
  QGIS_DEBUG: 0
  QGIS_SERVER_LOG_LEVEL: 0

web:
  # use django manage.py server
  command: debug

django:
  DEBUG: True
  # enable remote debugging
  command: dev
  # put your ip address of your interface to SITEURL and GEONODE_BASE_URL
  ALLOWED_HOSTS: "['geonode.dev','localhost','django']"
  SITEURL: http://192.168.1.5/
  GEONODE_BASE_URL: http://django:8000/
  # Settings for qgis server
  QGIS_SERVER_URL: http://qgis-server/
  # Settings for geoserver
  GEOSERVER_BASE_URL: http://geoserver:8080/geoserver/
  GEOSERVER_LOCATION: http://geoserver:8080/geoserver/
  GEOSERVER_PUBLIC_LOCATION: http://192.168.1.5:8080/geoserver/
  # GeoSAFE specific settings
  USE_LAYER_FILE_ACCESS: True
  INASAFE_LAYER_DIRECTORY: "/home/geosafe/media/"
  INASAFE_LAYER_DIRECTORY_BASE_PATH: "/usr/src/app/geonode/uploaded/"
  GEOSAFE_IMPACT_OUTPUT_DIRECTORY: "/home/geosafe/impact_layers"
  INASAFE_IMPACT_BASE_URL: "/output/"
  USE_LAYER_HTTP_ACCESS: False
  INASAFE_ANALYSIS_RUN_TIME_LIMIT: 600
  INASAFE_ANALYSIS_AREA_LIMIT: 1000000000

celery:
  DEBUG: True
  # enable remote debugging
  command: dev

inasafe_headless:
  INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR: /home/output/
  INASAFE_HEADLESS_DEPLOY_OUTPUT_URL: http://inasafe-output/output/
  QGIS_LOG_FILE: /tmp/inasafe/realtime/logs/qgis.log
  QGIS_DEBUG_FILE: /tmp/inasafe/realtime/logs/qgis-debug.log
  QGIS_DEBUG: 0
  INASAFE_WORK_DIR: /tmp/inasafe
  # enable remote debugging
  command: /start-celery.sh dev

inasafe_headless_analysis:
  INASAFE_HEADLESS_DEPLOY_OUTPUT_DIR: /home/output/
  INASAFE_HEADLESS_DEPLOY_OUTPUT_URL: http://inasafe-output/output/
  QGIS_LOG_FILE: /tmp/inasafe/realtime/logs/qgis.log
  QGIS_DEBUG_FILE: /tmp/inasafe/realtime/logs/qgis-debug.log
  QGIS_DEBUG: 0
  INASAFE_WORK_DIR: /tmp/inasafe
  # enable remote debugging
  command: /start-celery.sh dev
