version: '2'
services:

  rabbitmq:
    image: rabbitmq
    network_mode: "bridge"

  postgis:
    image: kartoza/postgis:9.4-2.1
    restart: on-failure
    volumes:
      - './pg/postgres_data:/var/lib/postgresql'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
    network_mode: "bridge"

  django:
    build: docker-geonode
    volumes:
      - '../src/geonode:/usr/src/app'
      - '../src/core:/usr/src/core'
      - '../src/geonode/geonode/static_root:/home/web/static'
      - '../src/geonode/geonode/uploaded:/home/web/media'
      - './logs:/var/log/'
    command: prod
    environment:
      - DATABASE_URL=postgres://docker:docker@postgis:5432/gis
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - DJANGO_SETTINGS_MODULE=geonode.settings
      - GEOSERVER_BASE_URL="http://geoserver:8080/geoserver/"
# Should be specified in docker-compose.override.yml. Because it depends on the
# host
#      - ALLOWED_HOSTS=['django',]
      - DEBUG=False
      - PYTHONPATH=/usr/src:/usr/src/app/
      - DJANGO_SETTINGS_MODULE=core.settings
      - ROOT_URLCONF=core.urls
      - SITEURL=http://localhost/
      - GEONODE_BASE_URL=http://nginx/
      - QGIS_SERVER_URL=http://qgis-server/
    links:
      - postgis
      - rabbitmq
    network_mode: "bridge"

  web:
    build: docker-nginx
    command: prod
    volumes:
      # I dont use volumes_from as I want to use the ro modifier
      - '../src/geonode/geonode/static_root:/home/web/static:ro'
      - '../src/geonode/geonode/uploaded:/home/web/media:ro'
      - './logs:/var/log/nginx'
    links:
      - django
#  Default exposed port.
#  Should be specified in docker-compose.override.yml
#    ports:
#      - "80:80"
    network_mode: "bridge"

  celery:
    build: docker-geonode
    restart: on-failure
    working_dir: /usr/src/app
    volumes:
      - '../src/geonode:/usr/src/app'
      - '../src/core:/usr/src/core'
    environment:
      - DEBUG=False
      - C_FORCE_ROOT=True
      - DATABASE_URL=postgres://docker:docker@postgis:5432/gis
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - PYTHONPATH=/usr/src:/usr/src/app/
      - DJANGO_SETTINGS_MODULE=core.settings
      - ROOT_URLCONF=core.urls
      - SITEURL=http://localhost/
      - GEONODE_BASE_URL=http://nginx/
      - QGIS_SERVER_URL=http://qgis-server/
    command: celery -A geosafe worker -l debug -Q default,cleanup,email,update,geosafe -n geonode.%h -B
    links:
      - rabbitmq
      - postgis
    network_mode: "bridge"
